/* Fixture views generated by Python/SQLite, NOT production telemetry. */
const colors = ["#F5C9B5","#E1CDBE","#CAD2C8","#B2D5D1","#ACDAD8","#BBE1DF","#C9E7E6","#D8EEED"];
const ramp = ["▁","▂","▃","▄","▅","▆","▇","█"];
let suite, index = 0, width = "auto";
const q = id => document.getElementById(id);
const date = ms => ms === null ? "no request evidence" : new Date(ms).toISOString();
function draw() {
  const current = suite[index], v = current.view;
  q("step").textContent = current.label;
  q("explanation").textContent = current.description;
  const pct = v.percentage === "?%" ? "0.0%" : v.percentage.replace(/^~/, "").replace(/^(\d+)%$/, "$1.0%");
  let digit = 0;
  q("percentage").replaceChildren(...Array.from(pct, ch => {
    const span = document.createElement("span");span.textContent = ch;
    span.style.color = ch === "." ? "#C0C5C9" : ch === "%" ? "#BBD5DA" : ["#FF0000","#FF1B1D","#FF393A"][Math.min(digit++, 2)];
    return span;
  }));
  q("bars").replaceChildren(...v.codes.map((code, i) => {
    const span = document.createElement("span");span.className = "cell";
    span.dataset.code = code;
    span.textContent = code === "?" || code === "-" ? ramp[0] : ramp[Number(code)];
    span.style.color = code === "?" || code === "-" ? colors[0] : colors[Number(code)];
    const bucket = v.buckets[i];
    span.title = bucket ? `${date(bucket.bucket === null ? null : bucket.bucket*300000)} / ${bucket.quality}` : "Unknown coverage";
    return span;
  }));
  q("row").style.maxWidth = width === "auto" ? "none" : `${width}ch`;
  q("anchor").textContent = date(v.anchor_ms);
  q("tokens").textContent = `R ${v.read.toLocaleString()} / W ${v.write.toLocaleString()} / U ${v.uncached.toLocaleString()}`;
  q("clock").textContent = date(current.now_ms);
  q("quality").textContent = `${v.quality} · ${v.codes.length} cells`;
  q("buckets").replaceChildren(...v.buckets.map((b, i) => {
    const node = document.createElement("div");node.className = "bucket";
    const title = document.createElement("b");title.textContent = b.bucket === null ? `${i+1}. Unused history` : `${i+1}. ${new Date(b.bucket*300000).toISOString().slice(11,16)} UTC`;
    const detail = document.createElement("div");detail.textContent = `${b.quality} · R ${b.read} / W ${b.write} / U ${b.uncached}`;
    node.append(title,detail);return node;
  }));
  q("previous").disabled = index === 0;q("next").disabled = index === suite.length-1;
  q("count").textContent = `Step ${index+1} / ${suite.length}`;
}
function freezeCheck(reason) {
  const before = q("row").textContent;
  draw();
  if (q("row").textContent !== before) throw new Error("Idle refresh changed the cache picture");
  q("status").textContent = `${reason}: exact picture retained, all twelve cells unchanged.`;
}
async function init() {
  const response = await fetch("history-vectors.json");
  if (!response.ok) throw new Error("Serve this demo through a local HTTP server");
  const data = await response.json();
  if (data.schema !== "cockpit-demo/v1" || data.fixture_only !== true) throw new Error("Invalid fixture schema");
  suite = data.suites[document.body.dataset.suite];
  if (!suite || suite.some(x => x.view.codes.length !== 12)) throw new Error("Missing twelve-cell test vectors");
  q("previous").addEventListener("click", () => {index--;draw();q("status").textContent="";});
  q("next").addEventListener("click", () => {index++;draw();q("status").textContent="";});
  q("reset").addEventListener("click", () => {index=0;draw();q("status").textContent="";});
  q("idle").addEventListener("click", () => freezeCheck("Idle + one day"));
  q("ttl").addEventListener("click", () => freezeCheck("TTL expired"));
  q("redraw").addEventListener("click", () => freezeCheck("Duplicate redraw"));
  q("width").addEventListener("change", event => {width=event.target.value;draw();});
  draw();q("status").textContent="Fixture engine loaded. No real cache or configuration is modified.";
  document.body.dataset.ready="true";
}
init().catch(error => {q("status").textContent=error.message;document.body.dataset.error="true";});
